### ISSUE TITLE
Add id to sample and source schemas

### ISSUE THREAD

**Issue by dhakim87** [biocore/microsetta-private-api#19]
Working my way through the yaml, I'm unclear on how the user can navigate the api in several places:

POST /accounts generates a new account, but does not return the account ID.  How do we get the id for the GET,PUT /accounts/{account_id} ?

Same issue in GET,POST /accounts/{account_id}/sources: No source ID is returned, so no id is available for GET,PUT,DELETE /accounts/{account_id}/sources/{source_id}

Same issue in samples, though this may be blocked until schema is modified.  We sometimes pass sample_barcode around, but the url appears to be expecting a uuid.  

Same issue in POST /accounts/{account_id}/sources/{source_id}/surveys, the GET seems fine.  

GET /kits/ should probably also return id fields in the objects for the same reasons as above

Should we add id fields to these model objects?

**Comment by AmandaBirmingham** [comment]
I believe that this issue is based on a misunderstanding of the yaml.  According to the yaml, the created ids ARE returned by all the posts mentioned ( /accounts, /accounts/{account_id}/sources, /accounts/{account_id}/sources/{source_id}/surveys ).  Per https://restapitutorial.com/lessons/httpmethods.html , the new id is returned via the location header:  " POST [returns] 201 (Created), 'Location' header with link to [e.g.] /customers/{id} containing new ID."  It is of course up to the implementation WE write to populate this header.

I do not understand the request regarding GET /kits/ ... can you clarify?

**Comment by dhakim87** [comment]
That should work for the POST operations I guess.  But what about the GETs that get all items in a collection?  GET /accounts/{account_id}/sources gives a list of sources with all of their data but excluding their id, so I don't know source is which if I want to access one of them.  GET /kits/ returns a collection of samples without individual ids and so should have the same problem?

**Comment by AmandaBirmingham** [comment]
Ah, now I understand the GET issue--great find!  You are right that the defined schemas `sample` and for `source` (which are returned from GETs in the api) do NOT include the ids.  That needs to be fixed :)
