### ISSUE TITLE
View/Edit/Delete Sample Information

### ISSUE THREAD

**Issue by dhakim87** [biocore/microsetta-private-api#49]
There are additional sample information fields (site, date, time, notes) that should be editable in the api.  Ensure these are included in PUT/POST for update/creation of samples.  Test to ensure this implementation is working.

**Comment by AmandaBirmingham** [comment]
Clarification: this api does NOT support CREATING a sample.  This is because (AFAIunderstand), samples are *created* when they are added to a kit and shipped out, which is not a process to which an AGP end user has any visibility.  So, a sample could exist in our db (as in, we sent it out) even though no user has ever decided to actually provide info for it ... it would have a lot of null values :)

The existing api's POST /accounts/{account_id}/sources/{source_id}/samples therefore does not create a *sample*--what it creates is an *association* between an existing (see above) but currently unclaimed sample and the source in question.  

If you want to set the actual *values* for that existing sample, like its site or date or notes (rather than its *association* to a source), it is necessary to use the PUT /accounts/{account_id}/sources/{source_id}/samples to "change" them (rather than "create" them), since there are already (null) values for all those fields in the (existing) sample record that was created when the kit went out.

This follows the RESTful guidances for http methods--POST used only to create new things (a new association) and PUT used to update existing things (an existing sample record whose creation was outside the scope of this api).  Honestly I find it a little confusing that both of these actions are part of the samples endpoint when they act on qualitatively different pieces of info (sample vs sample-to-source-association) but my recollection is that others in the group gagged when I set some of these endpoints up as referring to associations directly :D 

Another option would be to send sample values (date, notes, site, etc) in the POST, and then build the back-end to both create the new sample-to-source association and *also* update the sample record with new values.  I feel a little queasy about this since it seems to muddy up the separation of roles for different http methods, but maybe it would end up being less confusing in the long run ...?

**Comment by wasade** [comment]
Just to note, @AmandaBirmingham assessment is accurate: we are updating samples known a priori by the database, not creating them.

**Comment by AmandaBirmingham** [comment]
Also, just occurred to me to note: the api does not support deleting samples (for the reasons discussed above).  If you wanted to delete the *info* associated with a sample (site, datetime collected, etc), then I believe you would use the PUT to set those values to null, etc.  The actual sample "delete" endpoint deletes the *association* of the sample to the source, putting the sample back to being "unclaimed".  

When I think through this, I see that, if used stupidly, the existing api could lead to garbage info ... for example, imagine a user associates a sample to a source and fills out the sample info, but then decides to dissociate that sample from that source.  This would lead to a source that is unclaimed, but still has now-garbage info (site, datetime collected, etc) set for it, which is Not Right. I do not think the api layer itself can prevent this; it would have to be checked for and dealt with by the back end (for instance, by refusing to dissociate a sample that has info associated with it, or (more user-friendly), making an extra call behind the scenes to clear the info for any sample a user chooses to dissociate from a source). 

@wasade , can you please comment on how much effort, if any, you think is justified in the back end to defend against stupid paths through the api that could lead to this kind of situation?

**Comment by wasade** [comment]
@AmandaBirmingham if a sample is disassociated from a source, then I believe it would be correct for the information about that sample (i.e., collection date) to be stripped and reset to null.
