### ISSUE TITLE
Export of coarse location information

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-private-api#504]
I _believe_ the metadata pulldown is currently not exporting coarse location information. It would be valuable to restore this.

**Comment by AlohaPropolis** [comment]
I have also found these AGP-Microsetta metadata categories do not contain data, state, geo_loc_name, latitude, longitude. It would be nice if at least the state could be identified.

**Comment by AlohaPropolis** [comment]
***************************************************************

redbiom search metadata "HI" | wc -l
     470

redbiom search metadata "HI & 10317.X00179156" | wc -l
       1

redbiom search metadata "HI" > HI.txt

redbiom fetch samples --from HI.txt --context Deblur_2021.09-Illumina-16S-V4-100nt-50b3a2 --output HI.biom

biom summarize-table -i HI.biom -o HI.biom_summary.txt

The problem is sample 10317.X00179156 is not listed in HI.biom_summary.txt

****************************************************************
